M48
; DRILL file {KiCad 9.0.7} date 2026-03-08T21:18:41+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-08T21:18:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X107.65Y-112.5
T2
X112.15Y-112.5
T3
X106.5Y-97.5
X106.5Y-122.5
X156.5Y-97.5
X156.5Y-122.5
M30
